FROM node:18-alpine
WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm install

# Copy all source code
COPY . .

# Expose port
EXPOSE 5000

# Install nodemon globally
RUN npm install -g nodemon

# Start app in dev mode using nodemon
CMD ["nodemon", "--watch", "src", "--ext", "ts,js", "--exec", "ts-node", "src/server.ts"]
